version: '3'
services:
  backend:
    build: backend
    command: ["gunicorn", "--workers", "1", "-b", ":8080",  "server:app"]
    ports:
      - "8080:8080"

  frontend:
    build: frontend
    command: ["npm", "start"]
    ports:
      - '3000:3000'


volumes:
  node-modules: